// This file automatically generated by create_export_module.py
#include "../NumpyEigenConverter.hpp"


void import_08_02_double()
{
	// Without this import, the converter will segfault
	import_array();
	NumpyEigenConverter<Eigen::Matrix< double, 8, 2 > >::register_converter();
}

