// This file automatically generated by create_export_module.py
#include "../NumpyEigenConverter.hpp"


void import_13_05_double()
{
	// Without this import, the converter will segfault
	import_array();
	NumpyEigenConverter<Eigen::Matrix< double, 13, 5 > >::register_converter();
}

