// This file automatically generated by create_export_module.py
#include <NumpyEigenConverter.hpp>


void import_09_13_double()
{
	// Without this import, the converter will segfault
	import_array();
	NumpyEigenConverter<Eigen::Matrix< double, 9, 13 > >::register_converter();
}

