#include "NumpyEigenConverter.hpp"

// This file automatically generated by create_export_module.py
BOOST_PYTHON_MODULE(libnumpy_eigen)
{
	using namespace boost::python;
	import_array();

	  NumpyEigenConverter<Eigen::Matrix< int, 1, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 1, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 1, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 1, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 1, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 1, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 1, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 1, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 1, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 1, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 1, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 1, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 1, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 1, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 1, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 1, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 1, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 1, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 1, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 1, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 1, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 2, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 2, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 2, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 2, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 2, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 2, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 2, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 2, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 2, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 2, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 2, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 2, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 2, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 2, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 2, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 2, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 2, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 2, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 2, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 2, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 2, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 3, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 3, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 3, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 3, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 3, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 3, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 3, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 3, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 3, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 3, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 3, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 3, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 3, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 3, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 3, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 3, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 3, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 3, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 3, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 3, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 3, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 4, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 4, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 4, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 4, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 4, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 4, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 4, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 4, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 4, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 4, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 4, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 4, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 4, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 4, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 4, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 4, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 4, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 4, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 4, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 4, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 4, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 5, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 5, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 5, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 5, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 5, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 5, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 5, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 5, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 5, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 5, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 5, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 5, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 5, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 5, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 5, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 5, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 5, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 5, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 5, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 5, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 5, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 6, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 6, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 6, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 6, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 6, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 6, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 6, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 6, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 6, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 6, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 6, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 6, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 6, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 6, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 6, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 6, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 6, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 6, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, 6, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, 6, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, 6, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 1 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 2 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 3 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 4 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 5 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 6 > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, Eigen::Dynamic > >::register_converter();

	  NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic > >::register_converter();


}

