message("looking for matlab")

if (WIN32)
	SET(MATLAB_ROOT 
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.1;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.2;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.3;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.4;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.5;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.6;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.7;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.8;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.9;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.10;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.11;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.12;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.13;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.14;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.15;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.16;MATLABROOT]"
		"[HKEY_LOCAL_MACHINE\\SOFTWARE\\MathWorks\\MATLAB\\7.17;MATLABROOT]"
	)
	
	FIND_PATH(MATLAB_INCLUDE_DIR NAMES engine.h
	  PATHS
	  ${MATLAB_ROOT}\\extern\\include
	  NO_DEFAULT_PATH
	)
	
	FIND_LIBRARY(MATLAB_LIBRARIES NAMES libmat libeng
     PATHS
     ${MATLAB_ROOT}\\extern\\lib\\win32\\microsoft
	 ${MATLAB_ROOT}\\extern\\lib\\win64\\microsoft
     NO_DEFAULT_PATH
   )


else (WIN32)
	execute_process(COMMAND matlabroot
					OUTPUT_VARIABLE MATLAB_ROOT)

	FIND_PATH(MATLAB_INCLUDE_DIR NAMES engine.h
	  PATHS
	  /usr/include
	  /opt/local/include
	  /usr/local/include
	  /sw/include
	  MATLAB_ROOT
	  NO_DEFAULT_PATH
	)
	  
	FIND_LIBRARY(MATLAB_LIBRARIES NAMES libmat libeng
     PATHS
     /usr/lib
     /usr/local/lib
     /opt/local/lib
     /sw/lib
	 MATLAB_ROOT
     NO_DEFAULT_PATH
    )
endif (WIN32)